### ISSUE TITLE
Colors vanish on signs on Multiplayer servers

### ISSUE THREAD

**Issue by Etrit1** [ChristopherHaws/mc-text-utilities#100]
I'm not sure whats up with this one, or if its an issue with the mod.

I'm able to apply colors to the signs within the GUI, click done and the text is colored. But then it almost instantly flashes to all black text. 

But, it's working fine on Book and Quill so, that leads me to think it's an issue with the mod. ...but I really don't know. 

Any ideas?

**Comment by ChristopherHaws** [comment]
One of the options for the mod is the prefix character for formatting color codes. By default it is `§` but some servers (for example purpur servers) use the `&` character so you will need to change that in the settings.

**Comment by Etrit1** [comment]
I'll check that out. Thanks!

**Comment by boogarin** [comment]
> One of the options for the mod is the prefix character for formatting color codes. By default it is `§` but some servers (for example purpur servers) use the `&` character so you will need to change that in the settings.

how can i change the settings? have the same problem OP mentioned but couldn't find the config file.

**Comment by ChristopherHaws** [comment]
You can use the mod menu mod to access the settings.
