### ISSUE TITLE
Updated to 1.19.4 or 1.20?

### ISSUE THREAD

**Issue by allanonmage** [ChristopherHaws/mc-text-utilities#93]
I'm checking on the mods in my modpack and would like to know if you're going to update to 1.19.4/1.20.  I have your mod earmarked for inclusion, though it seems I didn't deploy it.  I told my players it might be several months after 1.20 releases before we could update, so if you're working on it, do you have an ETA?

**Comment by ChristopherHaws** [comment]
Updated versions have been published to curseforge and modrinth for 1.20.1. Sorry for the wait, been super busy.
